/* Generated By:JavaCC: Do not edit this line. FirstOrderLogicParserConstants.java */
package Parsers.FirstOrderLogic;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FirstOrderLogicParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NEGATION = 5;
  /** RegularExpression Id. */
  int CONJUNCTION = 6;
  /** RegularExpression Id. */
  int DISJUNCTION = 7;
  /** RegularExpression Id. */
  int IMPLICATION = 8;
  /** RegularExpression Id. */
  int REVERSE_IMPLICATION = 9;
  /** RegularExpression Id. */
  int DOUBLE_IMPLICATION = 10;
  /** RegularExpression Id. */
  int EXISTENTIAL_CUANTIFIER = 11;
  /** RegularExpression Id. */
  int UNIVERSAL_CUANTIFIER = 12;
  /** RegularExpression Id. */
  int NAME = 13;
  /** RegularExpression Id. */
  int FUNCTIONNAME = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"!\"",
    "\"/\\\\\"",
    "\"\\\\/\"",
    "\"->\"",
    "\"<-\"",
    "\"<->\"",
    "<EXISTENTIAL_CUANTIFIER>",
    "<UNIVERSAL_CUANTIFIER>",
    "<NAME>",
    "<FUNCTIONNAME>",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
