/* Generated By:JavaCC: Do not edit this line. PropositionalLogicParserConstants.java */
package Parsers.PropLogic;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PropositionalLogicParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NEGATION = 5;
  /** RegularExpression Id. */
  int CONJUNCTION = 6;
  /** RegularExpression Id. */
  int DISJUNCTION = 7;
  /** RegularExpression Id. */
  int IMPLICATION = 8;
  /** RegularExpression Id. */
  int REVERSE_IMPLICATION = 9;
  /** RegularExpression Id. */
  int DOUBLE_IMPLICATION = 10;
  /** RegularExpression Id. */
  int LETTER = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"!\"",
    "\"/\\\\\"",
    "\"\\\\/\"",
    "\"->\"",
    "\"<-\"",
    "\"<->\"",
    "<LETTER>",
    "\"(\"",
    "\")\"",
  };

}
